### ISSUE TITLE
New install with current code base can't start

### ISSUE THREAD

**Issue by ioscanner** [socfortress/CoPilot#294]
I can't do the first start of CoPilot with the latest version, wazuh indexer has not been added yet and it shouldn't have been added yet:

2024-09-16 02:13:00.368 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:23 - Resizing Wazuh index fields via scheduler...
2024-09-16 02:13:00.369 | INFO     | app.db.db_session:get_db_session:181 - DB session created
2024-09-16 02:13:00.369 | INFO     | app.db.db_session:get_db_session:181 - DB session created
2024-09-16 02:13:00.369 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
2024-09-16 02:13:00.373 | INFO     | app.db.db_session:get_db_session:189 - Closing DB session
2024-09-16 02:13:00.374 | ERROR    | app.db.db_session:get_db_session:185 - Error during DB session:
2024-09-16 02:13:00.374 | INFO     | app.db.db_session:get_db_session:189 - Closing DB session
ERROR [apscheduler.executors.default] Job "resize_wazuh_index_fields (trigger: interval[0:01:00], next run at: 2024-09-16 02:14:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copilot/backend/app/schedulers/services/wazuh_index_resize.py", line 25, in resize_wazuh_index_fields
    await resize_wazuh_index_fields_route()
  File "/opt/copilot/backend/app/connectors/wazuh_indexer/routes/monitoring.py", line 169, in resize_wazuh_index_fields_route
    return await resize_wazuh_index_fields()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copilot/backend/app/connectors/wazuh_indexer/utils/universal.py", line 557, in resize_wazuh_index_fields
    es_client = await create_wazuh_indexer_client("Wazuh-Indexer")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copilot/backend/app/connectors/wazuh_indexer/utils/universal.py", line 93, in create_wazuh_indexer_client
    raise HTTPException(
fastapi.exceptions.HTTPException
2024-09-16 02:13:00.377 | ERROR    | app.schedulers.scheduler:scheduler_listener:64 - Job wazuh_index_fields_resize crashed:

**Comment by taylorwalton** [comment]
Hey there, 

It sounds like you're experiencing an issue where CoPilot cannot be installed for the first time because the Wazuh-Indexer hasn't been added yet. The logs you’ve shared indicate that a scheduled job is running within CoPilot and attempting to resize Wazuh index fields.

From what I see in the logs, the crash appears to be related to the missing Wazuh-Indexer configuration. However, my understanding is that this shouldn’t affect CoPilot’s ability to start up and run normally, even if the scheduled job crashes due to the missing configuration.

Am I picking that up correctly?
Just to clarify, are you seeing something different on your end, where CoPilot fails to start entirely due to this issue?

If that’s the case, it would be helpful to understand more about how the failure is affecting your startup process. Do you think the system is treating this operation as critical, even though it shouldn’t be? Would you say that the crash is preventing any part of the app from functioning at all?

**Comment by ioscanner** [comment]
Correct CoPilot crashes and will not start up.  This is the first start and wazuh has not even been added yet.  Normally I add everything in the GUI once it is up and running.  This was a brand new install.  I even removed the images and pulled them again, same result each time:  fastapi.exceptions.HTTPException
2024-09-16 18:31:53.240 | ERROR    | app.schedulers.scheduler:scheduler_listener:64 - Job wazuh_index_fields_resize crashed:

**Comment by taylorwalton** [comment]
Hmm that is odd, could you share more details of your install procedure and share ALL logs during startup. It sounds like maybe facing an environment specific issue as I just implemented a fresh install with a client today and there were no issues.

**Comment by taylorwalton** [comment]
Hey there, is this still an issue? BTW: added in logic to not run the wazuh_index_resize if the indexer connector is not verified: https://github.com/socfortress/CoPilot/commit/2392a6aa927af14b794400da2c8d42c87af0d2b8#diff-2e5032bcd4a3eadc28235c5840cbb827b4e2430fbbc5a9d001ea32d472dc93f0

**Comment by SecurityArsenal** [comment]
I applied the update and I see it doesn't try to resize.  But it still doesn't come up.  I even reinstalled in to a KVM instead of using an LXC container just to see.  I think it has to do with SOCFortress AI Module: 

total 12
drwxr-xr-x 1 root root 4096 Jul  2 22:13 .
drwxr-xr-x 1 root root 4096 Jul  2 22:12 ..
drwxr-xr-x 1 root root 4096 Jul  2 22:13 dist
/usr/local/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:119: LangChainDeprecationWarning: The class `ChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 0.3.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
/usr/local/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
2024-09-26 15:52:20.234 | DEBUG    | __main__:<module>:10 - Starting SOCFortress AI Module Application
2024-09-26 15:52:20.234 | INFO     | __main__:<module>:19 - Starting SOCFortress AI Module Application
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
