### ISSUE TITLE
Office 365 deploy not working

### ISSUE THREAD

**Issue by SecurityArsenal** [socfortress/CoPilot#322]
2024-10-05 06:51:02.497 | INFO     | app.integrations.office365.services.provision:provision_office365:857 - Office365 integration is not yet provisioned.
2024-10-05 06:51:02.497 | INFO     | app.integrations.office365.services.provision:provision_office365:858 - Creating new Office365 block.
2024-10-05 06:51:02.509 | ERROR    | app.db.db_session:get_db_session:64 - Error during DB session: junk after document element: line 355, column 0
2024-10-05 06:51:02.511 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session

**Comment by taylorwalton** [comment]
What does your ossec.conf of the Wazuh Manager look like? Likely related to this issue on the discord: https://discord.com/channels/871419379999469568/1200829736042111028/1233289115911327806

**Comment by taylorwalton** [comment]
Hey there, just following up here. Do you have any updates?

**Comment by SecurityArsenal** [comment]
Sorry been crazy busy.  I did have sysmon enabled in the ossec.conf file, I disabled it, but not sure that is going to make a difference once it is in this state.  So guess that caused an issue.  Now is there a way to disable the 365 integration so it will work.  When it breaks it no longer gets alerts like it did before.  I think the last customer configured gives a few alerts. I tons of alerts come into the matrics:  

org.graylog2.throughput.input.1-sec-rate 362
org.graylog2.throughput.output.1-sec-rate  362

This was working before 365 integration so it seems to be related to the 0365 not working so it never processes the alerts:

This is the alert that happens all the time now.
2024-10-21 18:09:39.885 | INFO     | app.incidents.services.incident_alert:get_customer_code:210 - Failed to fetch customer code. Valid customer code field names are agent_labels_customer, data_office365_OrganizationId, syslog_customer, customer_code, cluster_node
2024-10-21 18:09:39.886 | ERROR    | app.db.db_session:get_db_session:64 - Error during DB session:
2024-10-21 18:09:39.888 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
ERROR [apscheduler.executors.default] Job "invoke_alert_creation_collect (trigger: interval[0:05:00], next run at: 2024-10-21 18:14:39 UTC)" raised an exception
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copilot/backend/app/schedulers/services/invoke_alert_creation.py", line 23, in invoke_alert_creation_collect
    await create_alert_auto_route(session=session)
  File "/opt/copilot/backend/app/incidents/routes/incident_alert.py", line 167, in create_alert_auto_route
    alert_id = await create_alert(create_alert_request, session)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copilot/backend/app/incidents/services/incident_alert.py", line 642, in create_alert
    customer_code = await get_customer_code(dict(alert_details._source))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copilot/backend/app/incidents/services/incident_alert.py", line 211, in get_customer_code
    raise HTTPException(
fastapi.exceptions.HTTPException
2024-10-21 18:09:39.896 | ERROR    | app.schedulers.scheduler:scheduler_listener:64 - Job invoke_alert_creation_collect crashed:

It looks like there should be a check to prevent this, and needs a way to remove the third party integrations if something goes wrong, or creds change or the service is no longer used.  Everytime I try to use the 365 integrations I end up having to roll back to snapshots to fix this.  I have never been able to get the 365 integrations to work.

**Comment by SecurityArsenal** [comment]
I tried to delete the customer that has the hung 0365 integration that is causing issues which happens to be the first customer.  It seems there are code errors trying to delete the customer.  I decommissioned it first then deleted the customer.  It seems to be missing "/" between port 55000 and agents

ERROR    | app.connectors.wazuh_manager.utils.universal:send_get_request:178 - Failed to send GET request to agents with error: Failed to parse: https://wazuh.local:55000agents
2024-10-21 18:48:39.936 | INFO     | app.customer_provisioning.services.wazuh_manager:get_agent_ids:187 - Response for Mac_socaana: {'success': False, 'message': 'Failed to send GET request to agents with error: Failed to parse: https://wazuh.local:55000agents'}

**Comment by taylorwalton** [comment]
> I tried to delete the customer that has the hung 0365 integration that is causing issues which happens to be the first customer. It seems there are code errors trying to delete the customer. I decommissioned it first then deleted the customer. It seems to be missing "/" between port 55000 and agents
> 
> ERROR | app.connectors.wazuh_manager.utils.universal:send_get_request:178 - Failed to send GET request to agents with error: Failed to parse: https://wazuh.local:55000agents 2024-10-21 18:48:39.936 | INFO | app.customer_provisioning.services.wazuh_manager:get_agent_ids:187 - Response for Mac_socaana: {'success': False, 'message': 'Failed to send GET request to agents with error: Failed to parse: [https://wazuh.local:55000agents'}](https://wazuh.local:55000agents'%7D)

Thanks for pointing this out, indded it does look like a `/` is missing. What endpoint did you call when making this request?

**Comment by SecurityArsenal** [comment]
This happens when clicked on decommission the provision and delete the customer.  I remember you had this in another place a few weeks ago too.  So might be good to just just check the code to see if you have more missing as this as been an issue more than once.

**Comment by taylorwalton** [comment]
https://github.com/socfortress/CoPilot/commit/74f26edc89003b5e473bc5fef9a5669ee88ce32b
