### ISSUE TITLE
copilot-backend will not start with the latest update

### ISSUE THREAD

**Issue by ioscanner** [socfortress/CoPilot#348]
the latest update to the backend copilot will not start:  copilot-backend-1  | 2024-12-04 19:32:55.530 | INFO     | app.db.db_populate:add_connectors_if_not_exist:199 - Added new connector: VirusTotal
copilot-backend-1  | Exception ignored in: <function Connection.__del__ at 0x7fb22be41d00>
copilot-backend-1  | Traceback (most recent call last):
copilot-backend-1  |   File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 1131, in __del__
copilot-backend-1  |   File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 339, in close
copilot-backend-1  |   File "/usr/lib/python3.11/asyncio/selector_events.py", line 864, in close
copilot-backend-1  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
copilot-backend-1  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
copilot-backend-1  | RuntimeError: Event loop is closed
copilot-backend-1 exited with code 3

**Comment by vidinburak** [comment]
Hello, 
I am experiencing a similar issue.


```
copilot-backend-1        | 2024-12-04 21:36:03.637 | INFO     | app.schedulers.scheduler:init_scheduler:82 - Initializing new scheduler...
copilot-backend-1        | 2024-12-04 21:36:03.650 | INFO     | app.schedulers.scheduler:init_scheduler:91 - Scheduling enabled jobs...
copilot-backend-1        | 2024-12-04 21:36:03.651 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
copilot-backend-1        | 2024-12-04 21:36:03.652 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
copilot-backend-1        | 2024-12-04 21:36:03.653 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
copilot-backend-1        | 2024-12-04 21:36:03.654 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
copilot-backend-1        | 2024-12-04 21:36:03.655 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
copilot-backend-1        | 2024-12-04 21:36:03.656 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
copilot-backend-1        | 2024-12-04 21:36:03.659 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: agent_sync
copilot-backend-1        | 2024-12-04 21:36:03.659 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: resize_wazuh_index_fields
copilot-backend-1        | 2024-12-04 21:36:03.659 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: invoke_alert_creation_collect
copilot-backend-1        | 2024-12-04 21:36:03.659 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: invoke_sigma_queries_collect
copilot-backend-1        | 2024-12-04 21:36:03.660 | INFO     | app.schedulers.scheduler:init_scheduler:95 - Starting scheduler...
copilot-backend-1        | 2024-12-04 21:36:03.693 | INFO     | app.schedulers.scheduler:init_scheduler:97 - Scheduler started.
copilot-backend-1        | 2024-12-04 21:36:03.697 | INFO     | __main__:shutdown_scheduler:206 - Shutting down scheduler
copilot-backend-1        | 2024-12-04 21:36:03.697 | INFO     | __main__:shutdown_scheduler:210 - Scheduler is running, shutting down now...
copilot-backend-1        | 2024-12-04 21:36:03.697 | INFO     | app.db.db_setup:ensure_scheduler_user_removed:331 - Ensuring scheduler user exists
copilot-backend-1        | 2024-12-04 21:36:03.707 | INFO     | app.auth.services.universal:remove_scheduler_user:185 - Scheduler user removed.
copilot-backend-1        | Exception ignored in: <function Connection.__del__ at 0x702698fa5d00>
copilot-backend-1        | Traceback (most recent call last):
copilot-backend-1        |   File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 1131, in __del__
copilot-backend-1        |   File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 339, in close
copilot-backend-1        |   File "/usr/lib/python3.11/asyncio/selector_events.py", line 864, in close
copilot-backend-1        |   File "/usr/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
copilot-backend-1        |   File "/usr/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
copilot-backend-1        | RuntimeError: Event loop is closed
copilot-backend-1 exited with code 1
```

**Comment by taylorwalton** [comment]
@ioscanner Have you added the below to the `.env` file as instructed in the video?

```
# VirusTotal
VIRUSTOTAL_URL=https://www.virustotal.com/api/v3
VIRUSTOTAL_API_KEY=REPLACE_ME
```

Link to video: https://youtu.be/fNybop2FTRE?si=jsp4KTNTmMFz9VFn&t=14

**Comment by ioscanner** [comment]
Ah, I didn't know there was a video, I thought it was just a normal update.  Was just testing to see the progress.
