### ISSUE TITLE
Incident Management - Alerts not updating

### ISSUE THREAD

**Issue by ioscanner** [socfortress/CoPilot#358]
After the last update something changed now Alerts are not being created in Incident Management - Alerts. I see the alerts in NAV bar Alerts, but none are added to the in Incident Management - Alerts. If I go to scheduler and click: 
Invokes alert creation collection. I get error occurred please try again

This was working before I updated to Velociraptor Recommended Artifact collection error fix for frontend and backend you did. But from what I saw I don't see how that would have impacted this.

Here are the logs:

copilot-backend-1 | ERROR [apscheduler.executors.default] Job "invoke_alert_creation_collect (trigger: interval[0:05:00], next run at: 2024-12-06 03:18:00 UTC)" raised an exception
copilot-backend-1 | Traceback (most recent call last):
copilot-backend-1 | File "/opt/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
copilot-backend-1 | retval = await job.func(*job.args, **job.kwargs)
copilot-backend-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
copilot-backend-1 | File "/opt/copilot/backend/app/schedulers/services/invoke_alert_creation.py", line 23, in invoke_alert_creation_collect
copilot-backend-1 | await create_alert_auto_route(session=session)
copilot-backend-1 | File "/opt/copilot/backend/app/incidents/routes/incident_alert.py", line 167, in create_alert_auto_route
copilot-backend-1 | alert_id = await create_alert(create_alert_request, session)
copilot-backend-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
copilot-backend-1 | File "/opt/copilot/backend/app/incidents/services/incident_alert.py", line 825, in create_alert
copilot-backend-1 | customer_code = await get_customer_code(dict(alert_details._source))
copilot-backend-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
copilot-backend-1 | File "/opt/copilot/backend/app/incidents/services/incident_alert.py", line 217, in get_customer_code
copilot-backend-1 | raise HTTPException(
copilot-backend-1 | fastapi.exceptions.HTTPException
copilot-backend-1 | 2024-12-06 03:13:02.851 | ERROR | app.schedulers.scheduler:scheduler_listener:65 - Job invoke_alert_creation_collect crashed:

I do have provisioned customers.  It was working just fine before the update.  I had Alerts and cases opened in Incident Management.  I even attempted to unprovision, delete the customers and reconfigure everything again but still the same result, so I went back to my snapshot before I deleted the customers just after the update so hopefully we can determine what happened.

**Comment by ioscanner** [comment]
I noticed this that the alerts from the source don't have agent_labels_customer or a valid customer code now.  But the full alert in the NAV bar Alerts have agent_labels_customer set. When you click the socfortress recommended settings when setting up the Incident Sources it doesn't have agent_labels_customer set.  Hopefully this helps.

2024-12-06 16:39:45.627 | INFO     | app.incidents.services.incident_alert:get_customer_code:202 - Fetching customer code for alert {'timestamp': '2024-12-05 14:56:32.430', 'timestamp_utc': '2024-12-05T14:56:27.370Z', 'rule_description': 'Administrators Group Changed', 'syslog_level': 'ALERT', 'syslog_type': 'wazuh', 'process_id': '1532', 'agent_name': 'NAME', 'rule_mitre_tactic': 'Defense Evasion, Privilege Escalation', 'rule_hipaa': '164.312.a.2.I, 164.312.a.2.II, 164.312.b', 'gl2_accounted_message_size': 4152, 'data_win_system_providerGuid': '{54849625-5478-4994-a5ba-3e3b0328c30d}', 'data_win_eventdata_subjectDomainName': 'domain', 'data_win_system_message': '"A member was added to a security-enabled local group.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-5-18\r\n\tAccount Name:\t\tuser$\r\n\tAccount Domain:\t\tdomain\r\n\tLogon ID:\t\t0x3E7\r\n\r\nMember:\r\n\tSecurity ID:\t\tS-1-5-21-1910921428-2839299906-3249843276-1188\r\n\tAccount Name:\t\t-\r\n\r\nGroup:\r\n\tSecurity ID:\t\tS-1-5-32-544\r\n\tGroup Name:\t\tAdministrators\r\n\tGroup Domain:\t\tBuiltin\r\n\r\nAdditional Information:\r\n\tPrivileges:\t\t-"', 'gl2_source_node': 'f46fdd47-e76f-40ef-b256-affb8c97d73b', 'decoder_name': 'windows_eventchannel', 'rule_level': 12, 'gl2_remote_port': 35110, 'data_win_system_processID': '1532', 'rule_nist_800_53': 'AC.2, IA.4, AU.14, AC.7', 'data_win_system_eventRecordID': '624343', 'rule_firedtimes': 1, 'rule_pci_dss': '8.1.2, 10.2.5', 'location': 'EventChannel', 'data_win_system_eventID': '4732', 'data_win_system_opcode': '0', 'rule_groups': 'windows, windows_security, group_changed, win_group_changed', 'true': 1733410587.567528, 'rule_group3': 'group_changed', 'rule_mitre_id': 'T1484', 'data_win_eventdata_targetSid': 'S-1-5-32-544', 'agent_id': '221', 'data_win_system_task': '13826', 'manager_name': 'mon', 'data_win_system_version': '0', 'rule_gpg13': '7.10', 'agent_ip': 'IP', 'message': '{"true":1733410587.567528,"timestamp":"2024-12-05T14:56:27.556+0000","rule":{"level":12,"description":"Administrators Group Changed","id":"60154","mitre":{"id":["T1484"],"tactic":["Defense Evasion","Privilege Escalation"],"technique":["Domain Policy Modification"]},"firedtimes":1,"mail":true,"groups":["windows","windows_security","group_changed","win_group_changed"],"pci_dss":["8.1.2","10.2.5"],"gpg13":["7.10"],"gdpr":["IV_35.7.d","IV_32.2"],"hipaa":["164.312.a.2.I","164.312.a.2.II","164.312.b"],"nist_800_53":["AC.2","IA.4","AU.14","AC.7"],"tsc":["CC6.8","CC7.2","CC7.3"]},"agent":{"id":"221","name":"FPS-LAP17","ip":"192.168.1.216"},"manager":{"name":"mon"},"id":"1733410587.7599329085","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-a5ba-3e3b0328c30d}","eventID":"4732","version":"0","level":"0","task":"13826","opcode":"0","keywords":"0x8020000000000000","systemTime":"2024-12-05T14:56:27.3702110Z","eventRecordID":"624343","processID":"1532","threadID":"6776","channel":"Security","computer":"FPS-LAP17.fps.local","severityValue":"AUDIT_SUCCESS","message":"\\"A member was added to a security-enabled local group.\\r\\n\\r\\nSubject:\\r\\n\\tSecurity ID:\\t\\tS-1-5-18\\r\\n\\tAccount Name:\\t\\tUSER$\\r\\n\\tAccount Domain:\\t\\tDOMAIN\\r\\n\\tLogon ID:\\t\\t0x3E7\\r\\n\\r\\nMember:\\r\\n\\tSecurity ID:\\t\\tS-1-5-21-1910921428-2839299906-3249843276-1188\\r\\n\\tAccount Name:\\t\\t-\\r\\n\\r\\nGroup:\\r\\n\\tSecurity ID:\\t\\tS-1-5-32-544\\r\\n\\tGroup Name:\\t\\tAdministrators\\r\\n\\tGroup Domain:\\t\\tBuiltin\\r\\n\\r\\nAdditional Information:\\r\\n\\tPrivileges:\\t\\t-\\""},"eventdata":{"memberSid":"S-1-5-21-1910921428-2839299906-3249843276-1188","targetUserName":"Administrators","targetDomainName":"Builtin","targetSid":"S-1-5-32-544","subjectUserSid":"S-1-5-18","subjectUserName":"USER$","subjectDomainName":"DOM","subjectLogonId":"0x3e7"}}},"location":"EventChannel"}', 'rule_tsc': 'CC6.8, CC7.2, CC7.3', 'data_win_system_systemTime': '2024-12-05T14:56:27.3702110Z', 'streams': ['66fb91ee4ae74f054e83b5f4'], 'data_win_system_channel': 'Security', 'gl2_remote_ip': 'ip', 'gl2_message_id': '01JEBN55NE002KSVZ4FM9JDKK2', 'rule_gdpr': 'IV_35.7.d, IV_32.2', 'rule_mail': True, 'gl2_source_input': '66fb91ef4ae74f054e83b637', 'id': '1733410587.7599329085', 'data_win_system_computer': 'fqdn, 'data_win_system_keywords': '0x8020000000000000', 'rule_id': '60154', 'data_win_eventdata_subjectUserName': 'USER$', 'data_win_eventdata_targetUserName': 'Administrators', 'rule_group2': 'windows_security', 'rule_group1': 'windows', 'data_win_system_level': '0', 'data_win_system_threadID': '6776', 'gl2_processing_error': 'Replaced invalid timestamp value in message <1d9f05f0-b319-11ef-9e3e-e2ab9d19623e> with current time - Value <2024-12-05T14:56:27.556+0000> caused exception: Invalid format: "2024-12-05T14:56:27.556+0000" is malformed at "T14:56:27.556+0000".', 'data_win_system_providerName': 'Microsoft-Windows-Security-Auditing', 'data_win_eventdata_subjectUserSid': 'S-1-5-18', 'msg_timestamp': '2024-12-05T14:56:27.556Z', 'data_win_eventdata_subjectLogonId': '0x3e7', 'rule_mitre_technique': 'Domain Policy Modification', 'source': 'IP', 'data_win_system_severityValue': 'AUDIT_SUCCESS', 'data_win_eventdata_targetDomainName': 'Builtin', 'data_win_eventdata_memberSid': 'S-1-5-21-1910921428-2839299906-3249843276-1188'}
2024-12-06 16:39:45.627 | INFO     | app.incidents.services.incident_alert:get_customer_code:206 - Checking for key agent_labels_customer
2024-12-06 16:39:45.627 | INFO     | app.incidents.services.incident_alert:get_customer_code:206 - Checking for key data_office365_OrganizationId
2024-12-06 16:39:45.628 | INFO     | app.incidents.services.incident_alert:get_customer_code:206 - Checking for key syslog_customer
2024-12-06 16:39:45.628 | INFO     | app.incidents.services.incident_alert:get_customer_code:206 - Checking for key customer_code
2024-12-06 16:39:45.628 | INFO     | app.incidents.services.incident_alert:get_customer_code:206 - Checking for key cluster_node
2024-12-06 16:39:45.628 | INFO     | app.incidents.services.incident_alert:get_customer_code:216 - Failed to fetch customer code. Valid customer code field names are agent_labels_customer, data_office365_OrganizationId, syslog_customer, customer_code, cluster_node

**Comment by taylorwalton** [comment]
Hey @ioscanner - thanks for sharing those details, really helpful! Indeed you have identified your problem, there must be a valid customer code (`agent_labels_customer, data_office365_OrganizationId, syslog_customer, customer_code, cluster_node`) within the event as mentioned in the error message.

It sounds like there is a lack of understanding as to what is required for alerts to be created. I recommend you seeing this video at the 5:36 mark: https://youtu.be/hC0JHY5WF-U?si=cOzUXlWUmgjsGasn&t=336

**Comment by ioscanner** [comment]
Yes, all of that is correct Graylog the indexes and streams are setup correctly.  I did have the cluster rule deleted.  When you go to the NAV bar and alerts: you can see the full rule and they are correct and have the agent_labels_customer assigned correctly to the customer_code provisioned for the customer.  But it is not getting set when the scheduler tries to get the alerts from the source for Incident Management - Alerts.  That is the output you have above.  The SOCfortress Recommends option doesn't seem to add the agent_labels_customer to the alerts being passed is my guess so it errors because it doesn't know who it belongs to because it is only getting the fields the recommended button provides.

**Comment by taylorwalton** [comment]
CoPilot does not set any customer code fields, nor does the SOCFortress Recommend option include that because we rely on the other systems (Wazuh or Graylog) to set that. 

I hear that you are saying you have followed the provisioning video exactly and see the `agent_labels_customer` for other events. But in the event that you previously shared where CoPilot is erroring out on, the `agent_labels_customer` does not exist. Since this field does not exist, CoPilot is functioning as expected. 

Now why the `agent_labels_customer` is not being set, if that is indeed defined in your Wazuh Group that the agent is apart of, would require investigation into your stack. Either there is still a configuration error within your stack setup, or maybe a bug within Wazuh where it does not always set the `agent_labels_customer`? If a Wazuh bug, this would be a new one heard to me. A possible workaround could be to create a Graylog Pipeline rule to evaluate if `agent_labels_customer` exists as it gets forwarded by Wazuh, and if it doesn't it adds the field with the customer code.

**Comment by ioscanner** [comment]
I used Copilot to create the customers so it should have configured the indexes correctly.  Sure enough there must be a bug in Copilot or wazuh when it provisions the customer.

I created 6 customers all within Copilot.  4 the mappings are correct, but 2 are not created correctly  They have this mapping instead:

full_message
text

gl2_accounted_message_size
long

gl2_message_id
keyword

gl2_processing_timestamp
date

gl2_receive_timestamp
date

message
text

source
text

streams
keyword

timestamp
date

**Comment by taylorwalton** [comment]
Im afraid your understanding is still not correct. The issue is not with your indexes, it is with a document (the one you previously provided) not having the `agent_labels_customer` field within it. Again, CoPilot does not set this. The Wazuh Manager does as it ingests the log from the endpoint agent.

### Log Flow goes like this:

Wazuh Agent -> Wazuh Manager (Sets `agent_labels_customer`) -> Graylog Stream(reads the `agent_labels_customer`) -> Graylog Pipeline (Does all the pipeline rules) -> Sends data to Wazuh Indexer as a document for the index.


### Alert Flow
Graylog makes search query to Wazuh Indexer based on the alert search criteria -> If a match, Graylog stores it -> Copilot reads from Graylogs store to fetch the `_id` and `index_name` (This is needed to get all the documents metadata) -> CoPilot queries the Wazuh Indexer to retrieve the document based on the `_id` and `index_name` -> Wazuh Indexer returns full document -> CoPilot verifies customer code (`agent_labels_customer` in your case`) exists -> CoPilot creates alert in the Incident Management platform

CoPilot has nothing to do with creating the `agent_labels_customer` field (again that is Wazuh Manager). CoPilot just uses this value to assign the alert to the correct customer. Since this is a crucial field, we report the error if the customer code field is not found

**Comment by ioscanner** [comment]
Yes, but when you provision the customer from Copilot it creates the indexes and groups.  It seems when I provision 6 customers 4 are created correctly and 2 are not.  This has to do with copilot not wazuh at this point.  Then my guess is after I fix it I have to find where the alerts are cached as it seems to still have the old alerts from the two customers that didn't get provisioned correctly.  I removed the two customers and now all indexes in wazuh have the correct mapping.

So it seems until I find where the alerts are cached because the indexes are removed from wazuh and graylog now but copilot still seems to see the old alerts and when it hits the alert without the agent_labels_customer set it errors and stops instead of moving on to the next alert.

Only place left I have not checked is in mongodb for graylog, if it has then cached there somewhere.  The bad indexes from the two customers are not in graylog anymore when I removed the customers it cleaned up both, but still has the old alerts from them somewhere that copilot sees them  I shouldn't have any older alerts before 1pm CST but they are still showing in copilot.  Any idea where it could be stored?

I am not sure why copilot had issues with two customers when provisioning them in wazuh.  It was not even the first and last one I added it was the 3 and 5 ones I added.

I tried to delete all alerts in wazuh, but the alert is still somewhere:
 app.incidents.services.incident_alert:get_customer_code:202 - Fetching customer code for alert {'timestamp': '2024-12-05 14:56:32.430'  I don't have any events that old in the customer indexes.  I deleted each customer and created and looked to ensure they are all mappings are correct.  I think it might have in graylog.  I am just not sure how to clean up old events it has.

**Comment by ioscanner** [comment]
Ok I found it.  So the issue was that copilot didn't create two customers correctly and it wrote bad alerts to the gl-events so when copilot tried to process it stopped, might be better to just log the error and keep processing and log that there could be an issue with customer index and provide the customer code.  After I cleared the events from gl-events_* it worked again: 

So two issues.  One there appears to be a bug in customer provisioning that it doesn't do the mapping correctly.  This then causes the error that it doesn't have the agent_labels_customer assigned.  I think better handling of the of errors when this happens in the scheduler invoke_alert_creation_collect  that it not just stop due to a single bad alert as this breaks everything, until resolved.  Could be be good to popup a notice in the customer page that index issues found for a customer so you know there was an error for a customer.

curl -k -X POST "https://graylog:your_password@wazuh-indexer-server:9200/gl-events*/_delete_by_query" -H 'Content-Type: application/json' -d '{
  "query": {
    "match_all": {}
  }
}'

**Comment by taylorwalton** [comment]
CoPilot does not write alerts to the `gl-events`. Graylog is the one that does that, CoPilot just reads from that index. Yes I'd expect when you rotate and delete the old gl-events_* indices, it functions again.

Im sorry but what mapping are you referring to? CoPilot does not do any index mapping. CoPilot is actually not even the one that is "technically" creating the index. Technically it is Graylog that is creating it within the Wazuh Indexer, but CoPilot is the one that invokes this action using the Graylog API. 

I hear your concern, but in my opinion, I like the idea of forcing the user to fix the customer code. But I could take a look at doing a try catch where it moves to the next alert, need to evaluate what that would look like in the long run

**Comment by ioscanner** [comment]
Sounds like graylog has a bug and you are going to get more support requests about it.  Do you have the command you send to graylog that invokes graylog to create the logs.  I will see if there is a bug report with graylog on it. I am using:  graylog-server                   5.2.12-1                       amd64        Graylog server  That is pretty far behind, but I seem to remember graylog 6 not working the last time I tested.  Is that working?  It could be just the old version of graylog has an issue but has been fixed in version 6.
