### ISSUE TITLE
Backend Issue Help (Python librairies)

### ISSUE THREAD

**Issue by 98m16** [socfortress/CoPilot#385]
Hello @taylorwalton

I'm facing the same issue on portainer.

Here is the logs:
```
2024-12-20 09:53:57.188 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:409 - Loading available integrations auth keys data for BitDefender.
2024-12-20 09:53:57.189 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:481 - Integration ID for BitDefender: 9
2024-12-20 09:53:57.189 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:483 - Found integration ID for BitDefender: 9
2024-12-20 09:53:57.189 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:409 - Loading available integrations auth keys data for BitDefender.
2024-12-20 09:53:57.190 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:481 - Integration ID for CATO: 10
2024-12-20 09:53:57.190 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:483 - Found integration ID for CATO: 10
2024-12-20 09:53:57.190 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:409 - Loading available integrations auth keys data for CATO.
2024-12-20 09:53:57.191 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:481 - Integration ID for CATO: 10
2024-12-20 09:53:57.191 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:483 - Found integration ID for CATO: 10
2024-12-20 09:53:57.191 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:409 - Loading available integrations auth keys data for CATO.
2024-12-20 09:53:57.192 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:481 - Integration ID for CATO: 10
2024-12-20 09:53:57.192 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:483 - Found integration ID for CATO: 10
2024-12-20 09:53:57.192 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:409 - Loading available integrations auth keys data for CATO.
2024-12-20 09:53:57.193 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:481 - Integration ID for CATO: 10
2024-12-20 09:53:57.193 | INFO     | app.db.db_populate:get_available_integrations_auth_keys_list:483 - Found integration ID for CATO: 10
2024-12-20 09:53:57.193 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:409 - Loading available integrations auth keys data for CATO.
2024-12-20 09:53:57.194 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:511 - Adding available integrations auth keys to the database.
2024-12-20 09:53:57.201 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: TENANT_ID for Office365
2024-12-20 09:53:57.206 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: CLIENT_ID for Office365
2024-12-20 09:53:57.214 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: CLIENT_SECRET for Office365
2024-12-20 09:53:57.219 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_TYPE for Office365
2024-12-20 09:53:57.223 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: APP_ID for Mimecast
2024-12-20 09:53:57.226 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: APP_KEY for Mimecast
2024-12-20 09:53:57.228 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: EMAIL_ADDRESS for Mimecast
2024-12-20 09:53:57.231 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: ACCESS_KEY for Mimecast
2024-12-20 09:53:57.233 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: SECRET_KEY for Mimecast
2024-12-20 09:53:57.236 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_KEY for SAP SIEM
2024-12-20 09:53:57.239 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: SECRET_KEY for SAP SIEM
2024-12-20 09:53:57.241 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: USER_KEY for SAP SIEM
2024-12-20 09:53:57.244 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_DOMAIN for SAP SIEM
2024-12-20 09:53:57.247 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_KEY for Huntress
2024-12-20 09:53:57.249 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_SECRET for Huntress
2024-12-20 09:53:57.252 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_KEY for CarbonBlack
2024-12-20 09:53:57.255 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_URL for CarbonBlack
2024-12-20 09:53:57.259 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_ID for CarbonBlack
2024-12-20 09:53:57.262 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: ORGANIZATION_KEY for CarbonBlack
2024-12-20 09:53:57.265 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: CLIENT_ID for Crowdstrike
2024-12-20 09:53:57.269 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: CLIENT_SECRET for Crowdstrike
2024-12-20 09:53:57.272 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: BASE_URL for Crowdstrike
2024-12-20 09:53:57.275 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: SYSLOG_PORT for Crowdstrike
2024-12-20 09:53:57.278 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_HOSTNAME for DUO
2024-12-20 09:53:57.280 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: INTEGRATION_KEY for DUO
2024-12-20 09:53:57.282 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: SECRET_KEY for DUO
2024-12-20 09:53:57.285 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: PUBLIC_TOKEN for Darktrace
2024-12-20 09:53:57.287 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: PRIVATE_TOKEN for Darktrace
2024-12-20 09:53:57.290 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: HOST for Darktrace
2024-12-20 09:53:57.293 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: PORT for Darktrace
2024-12-20 09:53:57.296 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: BASIC_AUTH_USERNAME for BitDefender
2024-12-20 09:53:57.299 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: BASIC_AUTH_PASSWORD for BitDefender
2024-12-20 09:53:57.302 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: WEBSERVER_HOSTNAME for BitDefender
2024-12-20 09:53:57.305 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: WEBSERVER_PORT for BitDefender
2024-12-20 09:53:57.307 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: GRAYLOG_PORT for BitDefender
2024-12-20 09:53:57.309 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_KEY for BitDefender
2024-12-20 09:53:57.312 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: API_KEY for CATO
2024-12-20 09:53:57.315 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: ACCOUNT_ID for CATO
2024-12-20 09:53:57.318 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: EVENT_TYPES for CATO
2024-12-20 09:53:57.320 | INFO     | app.db.db_populate:add_available_integrations_auth_keys_if_not_exist:536 - Added new available integration auth keys: EVENT_SUB_TYPES for CATO
2024-12-20 09:53:57.335 | INFO     | app.db.db_setup:create_available_network_connectors:254 - Creating available network connectors
2024-12-20 09:53:57.336 | INFO     | app.db.db_populate:load_available_network_connectors_data:563 - Loading available network_connectors data for Fortinet.
2024-12-20 09:53:57.340 | INFO     | app.db.db_populate:add_available_network_connectors_if_not_exist:644 - New available network_connector: {'network_connector_name': 'Fortinet', 'description': 'Integrate Fortinet with SOCFortress.', 'network_connector_details': "# [Fortinet Syslog Forwarding](https://help.fortinet.com/fa/faz50hlp/56/5-6-1/FMG-FAZ/2400_System_Settings/1600_Log%20Forwarding/0400_Configuring.htm)\n\nThis process involves configuring the Fortinet firewall to send logs to an external syslog server.\n\n### Step 1: Accessing the Firewall\n\nLog in to your Fortinet firewall using the web interface or FortiGate GUI:\n\n-   Open a web browser.\n-   Navigate to the IP address of the FortiGate unit (e.g., `https://192.168.1.99`).\n-   Enter your administrative credentials to log in.\n\n### Step 2: Configuring the Syslog Server\n\nOnce logged in, follow these steps to configure the syslog server:\n\n-   **Go to Log & Report**\n    -   Navigate to Log & Report on the left-hand sidebar.\n    -   Select Log Settings\n    -   Click on Log Settings to open the logging configuration options.\n-   **Add a Syslog Server**\n    -   Find the section labeled Syslog Servers and click on Create New.\n-   **Configure Syslog Server Details**\n    -   **Name:** Enter a recognizable name for your syslog server.\n    -   **IP/Domain:** Enter the IP address or domain name of your syslog server.\n    -   **Reliable:** Select whether to use TCP (reliable) or UDP (faster but less reliable) for log transmission.\n    -   **Port:** Specify the port number on which the syslog server is listening (default is 514).\n    -   **Facility:** Choose the syslog facility to be used (e.g., Local7).\n    -   **Source IP:** (Optional) Specify the source IP address if you want the logs to come from a specific interface IP.\n\n*   _Note_: The syslog format needs to be configured using FortiGate's CLI. Ensure that the format is set to rfc5424\n\n-   **Configure Filters (if needed)**\n    -   You can specify what kind of logs you want to send (e.g., traffic, event, virus, etc.). Select the appropriate log types.\n-   **Test Connection (if available)**\n    -   Some FortiGate models allow you to test the connection to ensure the syslog server is reachable.\n\n### Step 3: Saving the Configuration\n\nAfter entering all the necessary configurations:\n\n-   Click on OK or Apply to save the settings.\n-   The FortiGate firewall will now start forwarding logs to the specified syslog server based on your configurations.\n\n### Step 4: Verify Log Reception\n\nCheck your syslog server to verify that it is receiving logs from the Fortinet firewall. You might need to configure filters or settings on the syslog server side to properly categorize and display incoming logs.\n\n### Additional Considerations\n\n-   **Security:** Ensure that the network path between your Fortinet firewall and the syslog server is secure. Consider using VPNs or IPsec tunnels if the logs contain sensitive information.\n-   **Firewall Rules:** Ensure there are no firewall rules blocking the outgoing traffic on the port used for syslog.\n-   **Backup Configurations:** Always keep a backup of your firewall configurations before making significant changes.\n"}
2024-12-20 09:53:57.340 | INFO     | app.db.db_populate:add_available_network_connectors_if_not_exist:646 - Added new available network_connector: Fortinet
2024-12-20 09:53:57.359 | INFO     | app.db.db_populate:add_available_network_connectors_auth_keys_if_not_exist:735 - Checking for existence of available network_connectors auth keys.
2024-12-20 09:53:57.359 | INFO     | app.db.db_populate:get_available_network_connectors_auth_keys_list:699 - Getting available network_connectors auth keys.
2024-12-20 09:53:57.361 | INFO     | app.db.db_populate:get_available_network_connectors_auth_keys_list:707 - Network Connector ID for Fortinet: 1
2024-12-20 09:53:57.361 | INFO     | app.db.db_populate:get_available_network_connectors_auth_keys_list:709 - Found network_connector ID for Fortinet: 1
2024-12-20 09:53:57.361 | INFO     | app.db.db_populate:load_available_network_connectors_auth_keys:674 - Loading available network_connectors auth keys data for Fortinet.
2024-12-20 09:53:57.361 | INFO     | app.db.db_populate:add_available_network_connectors_auth_keys_if_not_exist:737 - Adding available network_connectors auth keys to the database.
2024-12-20 09:53:57.366 | INFO     | app.db.db_populate:add_available_network_connectors_auth_keys_if_not_exist:762 - Added new available network_connector auth keys: SYSLOG_PORT for Fortinet
2024-12-20 09:53:57.374 | INFO     | app.db.db_setup:ensure_admin_user:279 - Ensuring admin user exists
2024-12-20 09:53:57.672 | INFO     | app.auth.services.universal:create_admin_user:124 - Added new admin user with username: admin
2024-12-20 09:53:57.678 | INFO     | app.auth.services.universal:create_admin_user:125 - Admin user password: length=24 hashed='$2b$12$My4rhMus/x6EANMVseQLUuz5d0728mWfddNuU72Z73EdKn5xLZxY6' plain='H1gvxsVzMHivQZoif6bn2YX'
2024-12-20 09:53:57.679 | INFO     | app.db.db_setup:ensure_scheduler_user:296 - Ensuring scheduler user exists
2024-12-20 09:53:57.967 | INFO     | app.auth.services.universal:create_scheduler_user:157 - Added new scheduler user with username: scheduler
2024-12-20 09:53:57.968 | INFO     | app.auth.services.universal:create_scheduler_user:158 - Scheduler user password: 5Xw4lyAj1EO
2024-12-20 09:53:57.968 | INFO     | app.schedulers.scheduler:init_scheduler:82 - Initializing new scheduler...
2024-12-20 09:53:58.007 | INFO     | app.schedulers.scheduler:init_scheduler:91 - Scheduling enabled jobs...
2024-12-20 09:53:58.008 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
2024-12-20 09:53:58.009 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
2024-12-20 09:53:58.010 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
2024-12-20 09:53:58.011 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
2024-12-20 09:53:58.012 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
2024-12-20 09:53:58.013 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
2024-12-20 09:53:58.017 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: agent_sync
2024-12-20 09:53:58.018 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: resize_wazuh_index_fields
2024-12-20 09:53:58.018 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: invoke_alert_creation_collect
2024-12-20 09:53:58.018 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: invoke_sigma_queries_collect
2024-12-20 09:53:58.019 | INFO     | app.schedulers.scheduler:init_scheduler:95 - Starting scheduler...
2024-12-20 09:53:58.214 | INFO     | app.schedulers.scheduler:init_scheduler:97 - Scheduler started.
2024-12-20 09:53:58.220 | INFO     | __main__:shutdown_scheduler:206 - Shutting down scheduler
2024-12-20 09:53:58.220 | INFO     | __main__:shutdown_scheduler:210 - Scheduler is running, shutting down now...
2024-12-20 09:53:58.220 | INFO     | app.db.db_setup:ensure_scheduler_user_removed:331 - Ensuring scheduler user exists
2024-12-20 09:53:58.237 | INFO     | app.auth.services.universal:remove_scheduler_user:185 - Scheduler user removed.
Exception ignored in: <function Connection.__del__ at 0x7fbd0ff49da0>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 1131, in __del__
  File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 339, in close
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 864, in close
  File "/usr/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
  File "/usr/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
RuntimeError: Event loop is closed
```
Steps :
1- Modify the value of `env_file` to `stack.env`.
2- Set the `SERVER_API` to my server IP.
3- Replace all passwords vlaue to `password`

_Originally posted by @98m16 in https://github.com/socfortress/CoPilot/issues/357#issuecomment-2554967447_

**Comment by taylorwalton** [comment]
I have not tried to install through portainer though I wouldn't expect any modifications would need to be made. Can you share the exact docker compose and .env file you are using?

**Comment by taylorwalton** [comment]
Hey @98m16 - Have you had a chance to try @tuurhulselmans recommendation?

**Comment by rpolysec-gauntlet** [comment]
I'm getting the same error and my server_ip in the .env file is set to 0.0.0.0

**Comment by 98m16** [comment]
yes, it works 
thank you
